### ISSUE TITLE
How to make two server??

### ISSUE THREAD

**Issue by Ganggroid** [m-byte/Cigar#25]

**Comment by NikoCodex** [comment]
You can open a second port and get the server to connect through the second port.

**Comment by m-byte** [comment]
Since cigar is based on the master server, you can simply add another server by editing masterserver.ini. The line `regions = {"US-Fremont":1}` can be edited to add more servers. You can either change it to `regions = {"US-Fremont":2}` to let the client randomly connect to one of the two servers or `regions = {"US-Fremont":1, "Something":1}`

**Comment by Ganggroid** [comment]
@m-byte uh,,. but i don't use master server.... hmm..

**Comment by vram4** [comment]
Copy the server files folder to a different location, then edit gameserver.ini for a different port and run the server.
