### ISSUE TITLE
An error with the master and game server

### ISSUE THREAD

**Issue by NikoCodex** [m-byte/Cigar#28]
Hello! I am running the master and game server and i have noticed that both only run a master server?
I can run Cigar.exe but then i can't change gamemodes.
Please help.

**Comment by m-byte** [comment]
Shouldn't be too hard for a master at everything to figure this out...

**Comment by NikoCodex** [comment]
Never said i am a master, you're the one being rude now...

**Comment by m-byte** [comment]
Given the "thanks for nothing" comment, I'd consider it fair game... Many developers (including myself) spent countless hours on the code you are using. That makes up about 99% of the "nothing" you got from here... Answering issues also takes a lot of time, especially when someone opens lots of requests because they want you to customize the whole project just for them. That's the remaining 1%...

**Comment by NikoCodex** [comment]
Okay, here you go db6422e
